### ISSUE TITLE
Proposed process for managing de-listing of BOINC projects v0.2

### ISSUE THREAD

**Issue by G-UK** [gridcoin-community/Gridcoin-Tasks#201]
# De-listing
Project De-listing is the removal of a project from the Gridcoin Whitelist and Greylist.

Projects can be De-listed either automatically or manually at any time or as part of a regular review process by following the processes defined below.

Projects that are de-listed are not eligible for relisting for a period of 3 calendar months.

## Automatic Removal of a BOINC Project from Gridcoin (De-listing)
A project will be removed from the Gridcoin listings without the need for a vote if ANY ONE of the following requirements are met:
 a) The project has remained on the Greylist for a period of 60 consecutive days without being re-whitelisted
 b) The project remaining in the whitelist will cause an imminent security threat to the Gridcoin network
 c) The project Administrator requests the project is removed.

To de-list a project the following process must be followed:
1) Explanation for de-listing must be posted to the project thread on:
https://cryptocurrencytalk.com/forum/2436-projects/

2) A request is made to de-whitelist on the Gridcoin Slack # boinc_projects channel for an admin with whitelisting permissions to manually process.

## Manual Removal of a BOINC Project from Gridcoin (De-listing)
To manually de-list a project the following process must be followed:
1) Explanation for de-listing must be posted to the project thread on:
https://cryptocurrencytalk.com/forum/2436-projects/

2) Project is informed of the vote to de-list on the project forums and PM to project admin
    - Link to discussion provided to allow project “right of reply”

3) Poll is opened within the Gridcoin client in the form:
```
    * [Whitelist] Should the project "Project Name" be De-listed?
    * Answer Options: Yes, No, Abstain
    * Link to Discussion Thread provided
    * 2 Week duration
    * Magnitude & Balance
```
No other opinion must be given in the wallet poll to ensure neutrality.

Poll is successful if "Yes" gains greater than 50% of vote share and vote participation is above a weight of 7.5%

4) A request is made to de-list on a date no less than 2 weeks after completion of the vote on the Gridcoin Slack # boinc_projects channel for an admin with whitelisting permissions to manually process.

## Project Review Process
In order to ensure that the Gridcoin whitelist remains valid all projects will be reviewed every 6 months.

The project review process is as follows:
1) Opinion poll is raised taking the form of a multi-choice wallet vote.
```
    * [Whitelist Review]Which, if any projects should be reviewed for removal from the whitelist?
    * Answer Options: List of all Projects, None, Abstain
    * Link to this review document
    * 4 Week duration
    * Magnitude & Balance
```

Any projects gaining a network total vote weight of greater than 10% will be taken through the “Manual Removal of a BOINC Project from Gridcoin (De-listing)” process as previously detailed.

## Notes
  1) This process does not intend to define any guidelines or rules on what is considered a “valid” or “useful” project. It only intends to put in place the required processes to allow projects to be fairly delisted.

## Change Log
v0.2: 1st Feb 2018
- Added project review process
- Added project “right of reply”
- Added “cooldown” for de-listed proects
- Added 2 week delay to de-listing after vote finishes

v0.1: 20th Jan 2018
Initial proposal split from the main listing proposal to allow further discussion and investigate the idea to carry out regular project reviews.

See: https://github.com/gridcoin-community/Gridcoin-Tasks/issues/194

**Comment by G-UK** [comment]
#194

**Comment by NeuralMiner** [comment]
Maybe there should be a grace period before removal for projects that get voted out of the whitelist AS LONG AS it's not because of WU/project issues. Let's use the current Moo vote as an example; nothing wrong with the project itself or the WUs (it would fall under "green"). If the poll closed with "yes, remove project from the WL", I don't feel it would be fair for people to lose their mag right after poll closes in that case. I think there should be a two week grace period after the poll closes before the actual delist takes place to give people the chance to move their mag somewhere else instead of immediately losing it. 
Again, this should only apply to "green" projects. If the project isn't getting WUs or is constantly going down, has security issues, etc, then immediate removal would be appropriate.

**Comment by jring-o** [comment]
As we've discussed = )

I am a fan of a scheduled re-approval process instead of encouraging people to vote to delist projects they don't like.

Once a year, twice a year, or four times a year, we could revisit the projects on the whitelist to discuss whether we as a community continue to support the projects and their goals.

For example, March-April could be a time to revisit the whitelist along with September-October.

This process would encourage continued conversation on a project without hanging the threat of delisting over everyone's head until the agreed upon campaign time.

Of course, emergency delisting would still be a thing.

Some conversation around this idea has taken place here:
https://www.reddit.com/r/gridcoin/comments/7r23b8/a_few_brief_thoughts_on_whitelisted_projects/

An introduction to time-restricted campaigning can be found here:
https://www.npr.org/sections/itsallpolitics/2015/10/21/450238156/canadas-11-week-campaign-reminds-us-that-american-elections-are-much-longer

I'm happy to have very in-depth conversations on this subject! Ask questions or something.

**Comment by tcblack** [comment]
Thanks for this: I'm strongly in favor of policies that solve problems on their own.  This goes a long way to doing that.  
The only other point I would add is a question of fair distribution of points: If it can be demonstrated that a project is gaming the system and supplying more points than are reasonable, that is cause for greylisting/de-whitelisting as well.

Further: I agree with Neuralminer on giving people a window.

**Comment by G-UK** [comment]
Tried to incorporate everyones feedback in V0.2.

**Comment by NeuralMiner** [comment]
```Any projects gaining a network total vote weight of greater than 10% will be taken through the “Manual Removal of a BOINC Project from Gridcoin (De-listing)” process as previously detailed.```

I think that might be way too high; the last whitelist poll (ODLK) only got a 3.3% network vote weight. Having an option of every project and trying to get a 10% network weight on it will be near impossible in my opinion.

One option I can think of might be to take the top 3 (or 2, or 1, etc) of that poll and vote on their removal.

**Comment by G-UK** [comment]
Fair enough, that number was just a sort of placeholder. Probably something like 5% would be better.

I didn't want to make it so that we had to vote on removal of a number of projects as we could and hopefully will end up in a situation where people are happy with the whitelist.

**Comment by NeuralMiner** [comment]
I would say take the last ~5 polls involving the whitelist, average the participation among those, and go for something around that.

**Comment by G-UK** [comment]
Please See #213 for updated proposal.
