### ISSUE TITLE
Manual Reward Claim (MRC)

### ISSUE THREAD

**Issue by jring-o** [gridcoin-community/Gridcoin-Tasks#218]
Original Post:

https://steemit.com/gridcoin/@jringo/an-introduction-to-manual-reward-claim-mrc

Text copied below.

---

![Gridcoin Purple on White.png](https://steemitimages.com/DQmX37QfpRf45C9uKie2A9ibwypY6pzNwu7AsG9YqvEifrp/Gridcoin%20Purple%20on%20White.png)

---
---

<center><h1>CBR</h1></center>

---
---

So. 

Constant Block Reward (CBR) is in the development pipeline with a [proposal](https://steemit.com/gridcoin/@jringo/constant-block-reward-cbr-value-proposal-and-poll) released and a poll running to determine the block reward value (along with some other economic factors).

The implementation of CBR is expected to bring a drastic increase in staking difficulty to the network. This means greater security and more stability. It also means that the GRC required to stake once in 6 months is going to increase.

To briefly recap why this is important:

Gridcoin rewards participants who contribute their Idle Processing Potential (IPP) to distributed computing tasks on the BOINC platform. As a participant completes tasks, they earn Gridcoin in a Research Savings Account (RSA). This Earned Research Reward (ERR) is moved from the participant's RSA to their wallet when the participant stakes a block. In order to tie a participant's RSA with their BOINC Cross-Project ID (CPID), the participant must register a Beacon. All the calculations for the CPIDs, RSAs, and their ERRs are performed in something called the Neural Net. In order to ensure that the neural net doesn't get clogged calculating idle beacons, beacons expire after 6 months. This means that  participants must renew their beacon every 6 months. This means that in order to receive their ERR from their RSA, a participant must stake a block once every 6 months.

So if you have ERR in your RSA, but don't stake within 6 months, that ERR is lost.

The fact that you must stake to receive your ERR is an issue without CBR. With CBR, it becomes a problem.

---
---

<center><h1>The Current System</h1></center>

---
---

In general, individuals are encouraged to save or buy GRC so they can reach the level of "solo miner".  With the current idle-APR system and resulting low network difficulty, this is arguably reasonable: Buy a few hundred GRC, or buy some processing gear and earn that GRC, and then stake your ERR.

If you don't buy your GRC, you join the pool. The pool is an incredible tool run by BGB. I respect the pool and admire the work that BGB does for Gridcoin, however there are some drawbacks to this system. For one, many people end up joining the pool. This makes the pool a major staking entity, which is a form a centralization. 

Second, it is not possible to vote with your magnitude when in the pool. The pool currently hosts about 32% of the total network's magnitude. That is a significant amount of vote-weight tied up in the pool. BGB has set up internal voting for the pool which allows us to gauge interest, but those results are based on trust, and not an open-ledger.

Third, it can be argued that encouraging people to purchase GRC in order to receive their ERR by staking supports the price of GRC and is therefore good for the network at large. However, the pool provides a means to circumvent this artificial demand mechanism.

Without CBR, these issues as they stand provide enough incentive to develop a means of distributing ERR without forcing a participant to stake a block.

With CBR, more people will join the pool to receive their ERR, making all three of these issues more pronounced.

_I want to stress: The pool is great. BGB is awesome. The pool is not a problem. Being forced to stake to receive your ERR is a problem. The pool (and others) can exist in perpetuity. It provides, at the very least, a platform for simplified project management. How it functions and why it operates might need to change as the Gridcoin protocol evolves._

---
---

<center><h1>Manual Reward Claims (MRC)</h1></center>

---
---

So where does this leave us?

We need a way, other than staking, to move a participant's ERR from their RSA to their wallet. 

There have been a few ideas tossed around. My favorite is Manual Reward Claims (MRC).

With MRC, a participant can manually claim their ERR in an upcoming block for a small anti-spam fee. Standard staking could still serve to release ERR from a participants RSA to their wallet, or that function of staking could be removed.

You can think of MRC as similar to how rewards are claimed with steemit -- the push of a button.

As mentioned, developing MRC would require an anti-spam fee. An anti-spam fee is the same as the fee paid for making a transaction, sending a beacon, or registering a vote. This fee, let's call it the MRC-Fee, adds an economic tool to the Gridcoin network. Ask yourself, what do we do with these fees? 

A few possibilities:

- Distribute to stakers of blocks
- Distribute to the GRC Foundation
- Use to fund Gridcoin development through a treasury system
- Use to support BOINC projects, charities, relief efforts, causes, scientific research (grants?), and crowd-sourcing endeavors
- Burn to control inflation
- All of the above

---
---

<center><h1>Moving Forward</h1></center>

---
---

We are going to want to have MRC thought out before CBR is implement, so let's get this conversation rolling. Along with adding to, correcting, and refuting everything I said above, please share concerns and questions, and definitely share anything that can be added to the following two lists.

<h3>Problems</h3>

- Scaling (Currently 3,500 active beacons, 14,000 pool users, 960 blocks per day)
- Spam
- Security
- Logistics

<h3>Solutions</h3>

- High transaction protocols in development
- MRC-Fees
- Learning from existing platforms

---
---

For Science!

**Comment by jamescowens** [comment]
Based on the Discord conversation, I really liked the idea of making the MRC trigger a no-op unless the RSA account has accumulated more than x amount of research rewards. This can be enforced in the client and is a simple way to prevent transaction spamming.

28000 GRC/day distributed to 3500+14000 = 17500 researchers is 1.6 GRC per day average per researcher. So if we want to limit the transaction frequency to something like 2 transactions per block, this would be 960 * 2 = 1920 MRC transactions per day. This would be 28000/1920 or a RSA minimum of  14.5833... to trigger. This would mean the mean researcher would be able to claim every 14.58333... / 1.6 = 9.11458333.... days. (As a check on the calcs, 17500 / 9.11458333... = 1920.) To be safe for surges it might be a good idea to introduce a margin of error, so the RSA minimum should be 20 GRC?

Thoughts?

**Comment by jring-o** [comment]
I like it.

Thing to possibly also consider:

- Those with high balance might continue to claim their ERR through staking.
- An emergency retrieval for beacons which are about to expire -- though this is not necessary if Ravon's PR for beacons works.

---

I think we should also address the coinage possibility: Do we want to introduce coinage to staking probability? The longer coins are trying to stake, the more likely they are to stake. This would hopefully preclude any major balance holder from staking significant percentages of the chain in succession. The drawback expressed so far is that this is a minor disincentive to spend coins -- "I want to keep my GRC staking all the time so they are more likely to stake." I think this may be a pro and a con. And if its more of a con, it might be something to be solved in the future when more people possess and use GRC.

**Comment by jring-o** [comment]
The concern that coinage-staking addresses is more about ensuring that the blockchain:

A. is not staked by a few large holders (centralized in production)
B. is not secured by a few large holders (centralized in net weight)

The concern expressed (not necessarily mine) is that with CBR+MRC there will be little incentive for small holders to leave their coins on the network to stake because their chance of staking will be so minuscule and MRC means that they don't need to stake to get their ERR. Coinage-staking says to them, "leave them on long enough and you will stake. stay, be part of the net weight".

**Comment by tomasbrod** [comment]
Coin\*age weight is nice to incentivize small holders to stake, but it is vulnerable to attack. The attacker could make several outputs with whatever amount of coins, then just wait for them to build up enough weight to do 51. I can't cite, but someone was defending coinage weight by saying that time is money so this attack would still be expensive.

Moreover coinage weight further discourages spending

CBR reduces this disincentive to spend by removing age direct from interest calculation.

Offline staking, or delegation would help small holders, but it is not yet known how to do that.

**Comment by jamescowens** [comment]
I know what I am about to suggest is complicated, but what about using the "build-up" function for the coin age part? (This is the classic build-up curve in physics.... c(t) = 1 - e^(-wt). where w is the "build-up" or "decay" constant...)
`So line 530 of miner.cpp, instead of StakeTarget *= StakeTarget * CoinWeight, becomes something like ... StakeTarget *= StakeTarget * CoinWeight * dMaxChargeFactor * (1 - exp(-dLamba * (GetAdjustedTime() - (CoinBlock.GetBlockTime() & ~STAKE_TIMESTAMP_MASK) + nStakeMinAge)))

If MaxChargeFactor is = 1, then then this "builds up" to the original StakeTarget * CoinWeight value.

The timescale to get to 80% of the terminal value would be 0.8 = 1 - e^(-wt). This means that w for a given t at 80% would be w = -ln(0.2) / t. So dLamba for a 12 hour 80%  would be 1.609437.../43200 = 3.725555... * 10^(-5).'

**Comment by tomasbrod** [comment]
I never considered to use different (nonlinear) age to weight function. Good input.

**Comment by grctest** [comment]
Can we draw any lessons from how Steemit implements their reward balance claim mechanism?

https://github.com/steemit/steem/blob/807fb40ec137a987dc53cee6d8455c7b6c47aeed/libraries/wallet/include/steem/wallet/wallet.hpp#L1063

https://github.com/steemit/condenser/blob/245aa6f2f7c878863619766afbb140f9035f37be/src/app/components/modules/UserWallet.jsx#L793

**Comment by 47an** [comment]
anantshri have added 2 000 GRC to pot

And i would like to add 20 000 GRC to pot for MRC.

**Comment by sodom89** [comment]
I would like to add another 10 000 GRC to pot for MRC

**Comment by nconantj** [comment]
While this MRC idea would work to get newcomers staking faster, they still need some gridcoin to send their first beacon to start accumulating ERR. This requirement results in an investment requirement. Before MRC or any other similar idea can be implemented without requiring an initial investment or requesting coin from a faucet, there needs to be a way to get that first beacon out.

Perhaps that method could be allowing the first beacon advertised for the first cpid used in a wallet to be free. Once this problem is solved, perhaps eliminate the idea of the MRC. Instead, use the beacon age as a factor in the beacon transaction's weight, making its chances of staking ever higher. When the beacon transaction stakes, it automatically includes a beacon renewal transaction which is either deducted from available UTXOs or, if insufficient funds, deducted from the block or research rewards. Doing it this way, you're saying researchers will always be rewarded within six months regardless of balance and creating a stronger link to the research aspect of gridcoin.

I further suggest that superblocks be used to store accumulated ERR alongside the daily magnitudes. This way if a beacon expires, accumulated ERR is not lost.

The weight of an expired beacon would be raised exponentially every block until it stakes and renews within 24 to 48 hours. The research rewards would be the ERR from the last superblock the beacon was active.

There could be some abuse in this idea by letting people shut down their wallets for six or more months and still getting rewards. But at the same time, those abusers are reducing their chances of getting a pre-expiration stake and reducing their total research rewards because any research after beacon expiration would not count towards their research rewards.

**Comment by jamescowens** [comment]
The amount of Gridcoin needed to send an initial beacon is very small, 0.5 GRC. Free is not a good idea. Someone could very easily set up a wallet to advertise new beacons over and over and swamp the network in an attack. At least a small fee for beacon the beacon transaction provides some hurdle for that. So I do not agree with a free first beacon.

I also do not like the idea of introducing a hybrid PoST into our PoS consensus. The idea sounds seductive, but this also could be abused.

The storage of ERR alongside superblocks is already done. That is precisely what the snapshots in the accrual directory do. Rather than waste storage on the blockchain for this, each node computes the ERR for every CPID when the superblock is staked and then records the snapshot (1:1 correspondence with the SB on chain) in the accrual directory. The entire directory can be rebuilt on startup if it becomes corrupted or is missing. This also means that an expired beacon does not automatically mean ERR is lost. If the beacon is readvertised with the same CPID, the ERR is retained.

Also, there is no six month expiration period on rewards anymore. The beacon expires every six months, but as long as it is renewed, ERR will continue to accrue indefinitely.

I think MRC is the best mechanism to allow people to get paid earlier than otherwise would be warranted based on their balance, and the ability to charge higher fees when the button is pressed more often will discourage abuse and help fund the foundation.

**Comment by jamescowens** [comment]
The above two major PR's completed and merged, and currently being tested in testnet, this issue can be closed! :)

**Comment by 47an** [comment]
> anantshri have added 2 000 GRC to pot
> 
> And i would like to add 20 000 GRC to pot for MRC.

Payed my part 22000 in total to Jim. txid 5fb5baa386b95dd021ed2ab5c5b1bb6ee2bbaf741325158b2429ca04fa8bc0a4

**Comment by sodom89** [comment]
I payed my part of 10000 GRC to Jim, too. TXID 0b41e488f7752ce95921c09d4a20e3e98bdbf096bbcd96acc78fdb8cad73bd2e
