### ISSUE TITLE
Poll: GRC to create a poll

### ISSUE THREAD

**Issue by Aurum420** [gridcoin-community/Gridcoin-Tasks#253]
What minimum number of GRC should be needed to create a poll?

**Comment by Aurum420** [comment]
Tried to create a poll but it's broken. I have over 100,000 GRC but I have no idea how to tell if they're in less than 250 UTXOs, whatever they are.
![image](https://user-images.githubusercontent.com/60850550/192167413-2e6c208e-3e9b-4990-afdb-234a12576949.png)

**Comment by jamescowens** [comment]
It is not broken. It is simply the validation rules to submit a poll.

@Aurum420 go to "Send", select "Coin Control Features (advanced)" and then press the inputs button. This will show a tree with your UTXO's grouped by address. If you have too many smaller UTXO's so that the top 250 of them on a particular address do not add up to 100k GRC, then you can use the consolidate button to combine them, and/or do a transaction to yourself to move GRC from one address to another, depending on the situation.

**Comment by Aurum420** [comment]
I have exactly 2 GRC addresses and one has well over 100,000 GRC. Looks broken to me. I tried and got the same error message.

**Comment by Aurum420** [comment]
I tried that and got the same error message.

**Comment by elhippiesupremo** [comment]
What are the overall requirements to create a poll? Does having lots of coin automatically give one the power to put up a poll? Could someone with less be able to put forward a proposal based on the merits of the proposed poll itself?

**Comment by keegreil** [comment]
The 100k requirement is essentially an anti-spam measure, correct?  Only addresses with a significant stake in the network are allowed to post polls, which limits poll making to those who can be presumed to act in the best interest of the network (and they're own holdings).  Right now that's about 0.02% of supply, so I feel like that's still a reasonably low bar.  

There may be other anti-spam options though with different, and possibly desirable, governance effects.  For example, attach a more significant cost to making a poll, like 1k or 10k GRC.  That GRC probably goes to the foundation wallet or something.

Just getting the discussion going.  Without a more thorough community discussion I'd lean conservatively and keep it like it is, since that seems to be working.  Would love to hear from more senior members about what has and has NOT worked in the past.

**Comment by jamescowens** [comment]
That is correct. The current actual cost for a poll is 50 GRC + the transaction fees, which are typically about 0.05 or so. (They are more than a typical transaction, because the poll contract sent must include an attestation structure proving the meeting of the balance requirement that can be verified by every other node on the network.

The 100k balance requirement has been in place for many years. We have not experimented with alternative spam controls because this has worked well. If someone with a low balance feels strongly enough about an issue or initiative that they care about, they can approach one of the longstanding community members to sponsor the poll and actually make the poll on their behalf. This has the benefit of ensuring there is a level of community engagement already regarding the poll, which acts very successfully to prevent spam.

Even so, we have had spammy polls by individuals with sufficient balance to do so that do not follow proper polling procecdures. Perhaps this could be addressed by radically increasing the actual cost of the polls (probably accompanied by reducing the balance requirement). I think we have to be careful with this, however. There are no metrics that would allow us to predict a priori how that would actually affect poll creation.

I think the people that are voting on the survery poll right now on this issue have it right. The $100k balance requirement seems to be working pretty well as is. Leave it alone.

**Comment by jamescowens** [comment]
Closing this as the poll is finished regarding this matter.
