### ISSUE TITLE
Idea: "Proof of Work" Faucet for User Bootstrapping

### ISSUE THREAD

**Issue by makeasnek** [gridcoin-community/Gridcoin-Tasks#260]
**Problem Description**

Users require a few GRC to make a beacon and start solo mining. Our current suggestion is to obtain this GRC from a faucet, discord or exchange but:

- This is a barrier to entry even if it is overcome-able
- Obtaining coins from a faucet can take a while, faucets are often targeted for draining by people who don't mind filling in lots of CAPTCHAs. Some faucets have a minimum which means you need to use the faucet multiple times over the course of a day to reach the required amount for a beacon.
- Discord users are unable to verify that they are true "new users" and not just people asking for free coins, making it ripe for exploitation and exhaustion of volunteer GRC reserves
- Exchanges may be difficult to access or have minimums. Chances are their first GRC may cost them several if not 10+ dollars USD plus annoying waiting periods, time for transfers to clear, etc.

As Gridcoin continues to grow, the problems described above will increase in frequency and severity.

**Proposed Solution**
In order to solve this problem and reduce the hurdle involved in new users joining, a new type of faucet should be created. 

Here's how it works:

- User downloads and installs BOINC as normal, attaching to their favourite project(s) and earning credits under their own account.
- Faucet knows (via querying wallet) the credit to GRC ratio of each project. It adds 1 to this number, which becomes the required number of credits to "use" the faucet (REQUIRED_CREDIT). For example, normally it requires 500 credits to earn a GRC on Rosetta, so in order to receive 1 GRC from faucet you must have 501 credits. The list of projects and their required credits is shown on the faucet homepage. User would be encouraged to attach to a math project due to their relative lower difficulty.
- User changes username at project to their GRC address and goes to faucet.com. At faucet.com, they paste in a link to their profile URL at the project. Faucet.com verifies ACTUAL_USER_CREDIT >= REQUIRED_CREDIT and that the user has their username set to a valid-looking GRC address. If verification passes, faucet sends X GRC to the user's Gridcoin address.
- Any given username can only use this service once and cannot use it if a beacon already exists for this user.
- An added benefit of basing a faucet off BOINC credits is that existing BOINC users will be able to immediately get the GRC they need
- Neatly, this proposal does _not_ require that the faucet download the entire stats db from the project or have the 24-hour delay associated with superblocks, it can just query the user's profile page on demand. It also doesn't require the faucet to distribute or verify any work.

While this faucet would have to be filled up from time to time by the community, it would be cheaper than maintaining existing faucets. And by making it harder to "mine" GRC via the faucet than via solo mining, we insure nobody is incentivized to abuse it.

**Addl notes**

- Some projects will of course require GDPR export to be enabled for the faucet to query them
- Some project may not allow directly querying a user profile, those projects would be excluded from faucet participation
- Re: credit:grc ratio, of course it is not as simple as 500 credits = 1 GRC because RAC is measured by Gridcoin network, not raw credits. So maybe instead of +1 we want it to be x2 or any other formula we can come up with to insure it's more expensive to compute and use the faucet than just solo crunching normally. 

I intend to create a bounty for this once this proposal has been solidified via community feedback. Maybe, for example, there is some glaringly obvious reason this would not work.

**Comment by PrestackI** [comment]
I think it would be helpful for the proposal to outline the maximum amount of GRC granted by the faucet. 

Since they would not have any coins to stake with, we would want to include the cost of a Manual Rewards Claim (MRC) as well.

It would grant a one-time amount of 0.512 GRC:

Advertise Beacon Fee: 0.50 GRC
Manual Rewards Claim Fee: 0.01 GRC
Transaction Fee(s): 0.003 (one for the beacon, the claim, and to send the transaction)
Total = **0.513 GRC**


_At first glance_, the amount would appear to be large enough to incentivize people to gamify the system. 

However, I would propose we leave that determination to the data.

I propose we could test it by funding it with 100 coins (~194 payouts). Let it run until it is empty.

Then audit the distributions to test whether it helped them start up a solo staking wallet.

Let's set the success criteria as the beacon receiving a MRC at some point after they receive a deposit from the faucet.

I would say it was successful if it helped _one_ BOINCer get started with Gridcoin. 

But for good scientific form, let's put a success line at 25% of payouts (~49) were deemed successful.

**Comment by barton2526** [comment]
> It would grant a one-time amount of 0.512 GRC:
> 
> Advertise Beacon Fee: 0.50 GRC Manual Rewards Claim Fee: 0.01 GRC Transaction Fee(s): 0.003 (one for the beacon, the claim, and to send the transaction) Total = **0.513 GRC**

This is not sufficient to send a beacon. The wallet requires >1 GRC to send a beacon contract.

**Comment by PrestackI** [comment]
This can be marked as closed @makeasnek?

Since you already did it?

https://sciencestats.net/faucet
